name: intimin
channels:
  - conda-forge
  - defaults
dependencies:
  - jinja2=2.10
  - matplotlib=3.1
  - mdtraj=1.9
  - notebook=6.0
  - numpy=1.17
  - pandas=0.25
  - python=3.7
  - ruamel_yaml
  - yaml
